# Generated by Django 6.0.4 on 2026-04-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mayoreo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_mayoreo', models.PositiveIntegerField(default=1)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('es_granel', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
